---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: couchdb-data
  namespace: obsidian-sync
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
