---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: couchdb-credentials
  namespace: obsidian-sync
spec:
  encryptedData:
    COUCHDB_PASSWORD: AgB7G+pKFg6Gymze3/ROQJpuDBaouc/vkBN4jBRKM3Q7I6Y1w84LUgAT9A4oNo7bDmNvDjsGbWDih18IS1deGh3sRfgpedo1KumgpYrT70Ioumo1kKH1ZL+mUPe3dOaG6g4h1rgQTKrk2VgaMlBXHFjoIlFxP8/gj/JzpJnTBidnnFK6fu91FQ+az9b4gXdk2AWUHFFC+2h5fk8tYzJATOmZ+5Hk/lj4TCUH6HcWaqQ1kunjLeVVvE/7egqtm+k7rTMgLuKRhTYT/zgIxgqqQXnt/ZpdMoGT0eCQeeldxqgM0caKzqLhGWr1gzGsHSBk9zETn6ddoCKnOsc5mDz3QSqQOLbFQD52rn2tu8igruC495Rf38dMHd5lNuvQEaAZroaTaeTgmM4qoGhRWzMzshBZ/kCZFTA+nBCGGQvD5uxh0oM5nuMm+SOsWr33VV+gkkSYLTOpPoWYjd2hvcnMS80m4e7B09Ah9VEKVF6kXIYg03j5zp9m4MsZMBLtBBzA78mYun7cF+4lPhwES6PXERRqz3Flu8NO3PGqN+3cC11FruYOLGlf/xvYKLasOcOc0BFJKx06pLP9BRzLQxOiyvL5WEDWOKQslv7uSl2tL9d75y6JYFu59Un4pHhIsuIIdUbVGzQqslsgXDjVOMagd35U8qYV+Z0iuvcPZ6M9SfWCRmlC6EbXf1oSc9tUnhKfkZo/7LO/wtJMtUGu4cnT3TFqiDwgQn9g33fLGabgQeN6ZA==
    COUCHDB_USER: AgCqTwFntpaxh8a08/h6mpPgFgSmAHUN5vSLRn6zICOn9k4k8uka+LhXhGUleG7+pGArQY60OrpLGIiiqgGE/BFevgQMGo9o0WlcPXKxsIGePRwUOU5/BngDmdyHU3qaCCGG1CbB6ISpCkUY608U0Q/rBhSPN+YL3QVQ4RYoQI2gH/gZRqaMiyG3TeH5WNqvd6RUH+iOFEx0bOam7RjuJRFXufzATBR5DWIOFNwpa7nXqOprIWD+pzkLD7lHtq2pQMVII2XU+DU4dNQYafQTe9r0P+r9e5lANK+4CSomVph6YjZZRo1qOM16/CYYSD8te3+ZaFmKTa8vgTb/P3bOYwx2fA/GU22hpMNcqqYVFjvb5Hn6UMeXS6XC4K3nGe92+3y2dWRgbTrCVO6PHRlwEAfwFK7giddDdvDMnG2+AF5Qz27cS3lVCD3NiRz/LmsAZB1e1uYLPWDT9KhQhVG1/HwIaQyBzcZjnSe/8pHwOIzmsRBPjLiMAF+jLfNyXsqviVGErQXHrbM7hD1kMilEWD/vR+/4/0eZxknCz0KHD9sIB24k466PaY4bVHv2qFFL0ZhWUdTUksKxAz9p3+++3iuBjw6Ff2bOc5iRREwlhPDvonWIomh3PIJ73XuglyBTTVOUtwYTgBr+2CcLbSTgN8hMZPFkJ72zLd1p5nFWsH3uG8jNAcNjkw6/nT3Zk1lp230EZv8R3w==
  template:
    metadata:
      name: couchdb-credentials
      namespace: obsidian-sync
