---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: headscale-ui
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/qwqw-333/vps.git
    targetRevision: HEAD
    path: k8s/apps/headscale-ui
  destination:
    server: https://kubernetes.default.svc
    namespace: headscale-ui
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
