---
- name: Configure VPS
  hosts: all
  become: true

  vars:
    couchdb_user: "{{ vault_couchdb_user }}"
    couchdb_password: "{{ vault_couchdb_password }}"
    couchdb_domain: "{{ vault_couchdb_domain }}"
    origin_cert: "{{ vault_origin_cert }}"
    origin_key: "{{ vault_origin_key }}"
    docker_users:
      - "{{ app_user }}"

  roles:
    - base
    - users
    - docker
    - couchdb
